### ISSUE TITLE
Infra : 도커 이미지 pull Error (401, unauthorized)

### ISSUE THREAD

**Issue by HeeJohn** [now-here-5/be_now-here#24]
## ✅ Bug Report check list

- [x] [BUG] Docker 이미지 Pull 시 에러 발생

## BUG 개요

> OCI free tier 기간이 만료되면서, Oracle Container Registry를 더 이상 사용하지 못하게 됐습니다. 따라서 무료로 제공하는 용량은 적지만, Github에서 제공하는 Container registry를 이용하려고 했습니다. 이에 따라 배포 파이프라인을 수정하였고, 그 과정에서 아래 이슈를 발견했습니다.

<br>

- **문제 설명**: registry로 로그인은 가능하나, Docker 이미지를 GitHub Container Registry에서 Pull할 때 Unauthorized 에러가 발생합니다.
- **문제 원인**: 인증이 제대로 되지 않거나, 최신 태그와 Digest 정보를 가져오는 데 문제가 있습니다.
- **재현 방법**:
  1. GitHub Container Registry에 로그인합니다.
  2. `docker pull` 명령어로 이미지를 Pull 시도합니다.
  3. Unauthorized 에러가 발생합니다.
- **문제가 발생한 파일**: GitHub Actions 스크립트 파일 - 아래는 배포 과정에서 로그입니다. 

```bash
======CMD======
DEPLOYMENT_DIR="/home/username/app"
if [ ! -d "$DEPLOYMENT_DIR" ]; then
  echo "Directory $DEPLOYMENT_DIR does not exist. Creating it."
  mkdir -p "$DEPLOYMENT_DIR"
fi
cd "$DEPLOYMENT_DIR"
# GitHub Container Registry 로그인
echo *** | docker login ghcr.io -u HeeJohn --password-stdin
# Docker 이미지 Pull
if ! sudo docker pull ghcr.io/now-here-5/be_now-here/server-image:lastest; then
  echo "Failed to pull Docker image"
  exit 1
fi
sudo docker stop now-here-server || true
sudo docker rm now-here-server || true
if ! sudo docker run -d --name now-here-server -p 8080:8080 \
  -e DB_HOST=*** \
  -e DB_PORT=*** \
  -e DB_NAME=*** \
  -e DB_USERNAME=*** \
  -e DB_PASSWORD=*** \
  -e XOR_KEY=*** \
  -e SLACK_WEBHOOK_URL=*** \
  -e SLACK_INQUIRY_WEBHOOK_URL=*** \
  ghcr.io/now-here-5/be_now-here/server-image:lastest; then
  echo "Failed to run Docker container"
  exit 1
fi
# Show container logs for debugging
sudo docker logs now-here-server
======END======
err: WARNING! Your password will be stored unencrypted in /home/***/.docker/config.json.
err: Configure a credential helper to remove this warning. See
err: https://docs.docker.com/engine/reference/commandline/login/#credentials-store
out: Login Succeeded
err: Error response from daemon: Head "https://ghcr.io/v2/now-here-5/be_now-here/server-image/manifests/lastest": unauthorized
out: Failed to pull Docker image
```

## TODO

- [x] 로그 분석해서 에러가 발생하는 구간 파악합니다.
```bash
out: Login Succeeded ## 로그인은 성공.
err: Error response from daemon: Head "https://ghcr.io/v2/now-here-5/be_now-here/server-image/manifests/lastest": unauthorized ## pull 자체는 실패 (401)
out: Failed to pull Docker image
```
- [x] PAT 권한 확인하고, VM에 직접 접속해서 PAT와 함께 docker 이미지 pull를 시도합니다. (네트워크 문제인지 파악)
- 권한 이상 x
![image](https://github.com/user-attachments/assets/b0833c59-6b2b-4376-863c-689e4439b154)
- 로컬에서 PAT로 로그인 후 PULL 시도 실패
![image](https://github.com/user-attachments/assets/ba0298a7-fb13-420f-80ee-245f81c58021)

- [x] 유사한 케이스가 있는지 구글링합니다. 
- [GitHub Issue: Docker 인증 문제](https://github.com/docker/for-mac/issues/6704)
- [x] Github Registry 공식문서 확인해서 권한 문제에 대해서 확인합니다. 
- [github packages permission](https://docs.github.com/en/packages/learn-github-packages/about-permissions-for-github-packages)

## 파악된 문제와 해결 방안 :
> 여러번의 YML 파일 수정과 jobs 실행을 통해 문제를 해결하긴 했으나, 정확한 원인은 파악하지 못했습니다. 문제를 해결하는 과정에서 "linux 자체의 super user 권한과 github container registry에 대한 접근 권한이 충돌할 수 있나?" 라는 생각이 들었고 다음과 같은 절차를 통해 테스트해본 결과 문제가 해결되었습니다. 

1. 로컬에서 OCI VM으로 접근 (SSH)
2. ` echo ${{PAT}} |  docker login ghcr.io -u HeeJohn --password-stdin ` 으로 ghcr 에 로그인
3. ` docker pull ghcr.io/now-here-5/be_now-here/now-here-server:lastest ` 로 이미지 pull 
4.   Unauthorized 문제 없이 pull 성공

> 변경 사항 : `sudo`  제거
``` bash 

## 변경 전
 if ! sudo docker pull ghcr.io/now-here-5/be_now-here/now-here-server:lastest; then

## 변경 후
 if ! docker pull ghcr.io/now-here-5/be_now-here/now-here-server:lastest; then
```
